[package]
name = "docker"
version = "0.0.1"
edition = "2021"
repository = "https://github.com/nkia-christoph/pop-launcher-plugin-docker"
license = "GPL-3.0-only"
authors = ["Christoph Kröppl <ch.kroeppl@gmx.at>"]
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pop-launcher = "1.1.0"
docker-api = "0.14"
tokio = { version = "1.35.0", features = ["rt"] }
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"

[[bin]]
name = "docker"
path = "src/main.rs"

[profile.release]
codegen-units = 1
lto = true
strip = true
